#include <cstdio>
#include <string>

using namespace std;


int main(){
 string s ="TTGCCACATCCACTGTGTACCAAATTTGGCTGTCTAAAAAGATTAGTCTGTAAATGTAAGAGGGCCATGTTAGGATCGAGTGCACGCTAAAAAGTGCTCCCTGATTTCACTATAGAAGTGGTCTAGGTTCATAGGCGTATTCGGTCTAGTGGTGCTGGATCTCTCTCCATGCTGTTCCGGTACAAAAGCAGTGCCTTGGGCTCTTTAACTAACCTCCACTTATTCCTCTCGGAAGTGCCCGAGCTATTCGGCACGAACGGCCAGAACAATTGACTTGTCACAGGAGCTTACAATCCCGCGTCCCAGGATCAGATTGTAGTGTACCGGAGATATAAGCTAAGATTGACCAAACTAGGTCGTCACTCGGGACAACGTCGTTACGTCGTGAGGCCCCAAGTGCGAACGGTAAGGATTACATTTGGTCGTATATATAGTACTACGCAGCTCCGCAGAATCTCTGAGTCACTCATCCTAAAAGGACCTATGAAGCGCGTATAACGGGGCGTCAGTACGGAATGAAGCAACCAACTGGGTATGGCTAGATTTTACAGGGAAGTTTTCGCGTCAAGACCGAAGGAACTGGGGTTGAAAACACTCGGGAGGGGCGATTTTGACCCTGACGGTCTGGTGGTGGTACACCTTGGCGGATCTTGTCGGCCTGCTTGGCTGAACACCCAGAGTCCCGTGGTTTAGATATATGAACGGCTAGCTAGGTGCAACGTCATATAGCCTCGACATCCCTGTTCCTACGTGCAGTATTCTTGGAGCGCATCGAAATAAACAAGTATGGTCCGCACGTGTCCGGCCCTCGTGCGAAAGGACTCTGTCAGATCAGAACGCAATAGCATGATCAATCGTTAGCGCGATGGTATAGTAAGGAGTCGAGACACGGTTATTAACTTGGAGTGGTGTATCGTGTCGCGGATTTTCAGATAGAGACGGCTGTCTTGTAGGAAAAGCGAAAGATAGAAGGACTTCAGGACTC"; 
 int count[4] = {0};
 for(int i = 0; i < s.size(); i++) {
  if(s[i] == 'A') count[0]++;
  else if(s[i] == 'T') count[1]++;
  else if(s[i] == 'G') count[2]++;
  else if(s[i] == 'C') count[3]++;
 }

 printf("%d %d %d %d\n", count[0], count[3], count[2], count[1]);
return 0;
}
